"""
Surgical Annotator — VLM Service (Fine-tuned PaliGemma 2)
Drop-in replacement for vlm_service.py that uses a locally-exported,
domain-specific organ classifier instead of a general-purpose Ollama model.

This file is regenerated by training/export_model.py after each training run.
Activate by setting VLM_BACKEND=finetuned in config.py or environment.
"""

import json
import logging
import math
from pathlib import Path

import cv2
import numpy as np
import torch
from PIL import Image
from transformers import AutoProcessor, PaliGemmaForConditionalGeneration

from app.config import FINETUNED_MODEL_PATH, ABDOMINAL_ORGANS

logger = logging.getLogger(__name__)

PROMPT        = "Identify the highlighted surgical organ. Answer with the organ name only:"
OVERLAY_COLOR = (0, 255, 0)
OVERLAY_ALPHA = 0.3
CROP_PADDING  = 20


class VLMService:
    """Organ identification via fine-tuned PaliGemma 2 (fully local, no Ollama)."""

    def __init__(self):
        self.model:      PaliGemmaForConditionalGeneration | None = None
        self.processor:  AutoProcessor | None = None
        self.organ_list: list[str] = []
        self._loaded     = False
        self.device      = _detect_device()

    def is_available(self) -> bool:
        """True if the exported model directory exists."""
        return Path(FINETUNED_MODEL_PATH).exists()

    def identify_organ(self, image: np.ndarray, mask: np.ndarray) -> dict:
        """
        Identify the organ in the masked region.
        Returns {"label": str, "confidence": float}.
        """
        self._ensure_loaded()
        if not self._loaded:
            return {"label": "unknown", "confidence": 0.0}

        try:
            crop = _prepare_masked_image(image, mask)
            return self._infer(crop)
        except Exception as e:
            logger.error("Fine-tuned VLM inference failed: %s", e)
            return {"label": "unknown", "confidence": 0.0}

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return

        model_path = Path(FINETUNED_MODEL_PATH)
        if not model_path.exists():
            logger.error(
                "Fine-tuned model not found at '%s'. "
                "Run training/export_model.py to export a checkpoint.",
                model_path,
            )
            return

        logger.info(
            "Loading fine-tuned PaliGemma 2 from '%s' on %s...",
            model_path, self.device,
        )
        self.processor = AutoProcessor.from_pretrained(str(model_path))
        self.model = PaliGemmaForConditionalGeneration.from_pretrained(
            str(model_path),
            torch_dtype=torch.float32,
        ).to(self.device)
        self.model.eval()

        organ_list_path = model_path / "organ_list.json"
        if organ_list_path.exists():
            self.organ_list = json.loads(organ_list_path.read_text())
        else:
            self.organ_list = list(ABDOMINAL_ORGANS)

        self._loaded = True
        logger.info(
            "Fine-tuned VLM ready — %d organ classes on %s.",
            len(self.organ_list), self.device,
        )

    @torch.no_grad()
    def _infer(self, pil_image: Image.Image) -> dict:
        inputs = self.processor(
            images=pil_image,
            text=PROMPT,
            return_tensors="pt",
        )
        inputs = {
            k: v.to(self.device)
            for k, v in inputs.items()
            if isinstance(v, torch.Tensor)
        }

        # Score each organ by the log-probability of its first token.
        # This is a single forward pass (no auto-regressive loop) so it's fast.
        outputs = self.model(**inputs)
        next_token_logits = outputs.logits[:, -1, :]       # (1, vocab_size)
        log_probs         = torch.log_softmax(next_token_logits, dim=-1)

        organ_scores: dict[str, float] = {}
        for organ in self.organ_list:
            toks = self.processor.tokenizer.encode(organ, add_special_tokens=False)
            if toks:
                organ_scores[organ] = log_probs[0, toks[0]].item()

        if not organ_scores:
            return {"label": "unknown", "confidence": 0.0}

        # Normalise to probabilities over the organ set (softmax in log space)
        max_lp     = max(organ_scores.values())
        exp_scores = {o: math.exp(lp - max_lp) for o, lp in organ_scores.items()}
        total      = sum(exp_scores.values())
        probs      = {o: v / total for o, v in exp_scores.items()}

        best_organ = max(probs, key=probs.get)
        confidence = round(probs[best_organ], 4)

        if best_organ not in ABDOMINAL_ORGANS:
            best_organ = "unknown"

        return {"label": best_organ, "confidence": confidence}


# ======================================================================
# Helpers (shared preprocessing — must match vlm_service.py exactly)
# ======================================================================

def _detect_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    if torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def _prepare_masked_image(image: np.ndarray, mask: np.ndarray) -> Image.Image:
    h, w  = mask.shape
    rows  = np.any(mask, axis=1)
    cols  = np.any(mask, axis=0)
    if not rows.any():
        return Image.fromarray(image)

    rmin, rmax = np.where(rows)[0][[0, -1]]
    cmin, cmax = np.where(cols)[0][[0, -1]]
    rmin = max(0, rmin - CROP_PADDING)
    rmax = min(h - 1, rmax + CROP_PADDING)
    cmin = max(0, cmin - CROP_PADDING)
    cmax = min(w - 1, cmax + CROP_PADDING)

    crop      = image[rmin:rmax + 1, cmin:cmax + 1].copy()
    mask_crop = mask[rmin:rmax + 1, cmin:cmax + 1]
    overlay   = crop.copy()
    overlay[mask_crop] = OVERLAY_COLOR
    cv2.addWeighted(overlay, OVERLAY_ALPHA, crop, 1 - OVERLAY_ALPHA, 0, crop)
    return Image.fromarray(crop)
